nanopolish: /home/isac/Software/nanopolish
minimap2: /usr/local/bin/minimap2 
nanopore-methylation-utilities: /home/gmoney/repos/nanopore-methylation-utilities
reference: /kyber/Data/Nanopore/Analysis/gmoney/snake_test/dat/methylation_example/reference.fasta
out: /kyber/Data/Nanopore/Analysis/gmoney/snake_test
fastqdir: /kyber/Data/Nanopore/Analysis/gmoney/snake_test/dat/methylation_example
fast5: /kyber/Data/Nanopore/Analysis/gmoney/snake_test/dat/methylation_example/fast5_files
